storage:
  type: inMemory
  stopwordsFilePath: ./data/stopwords

index:
  maxResults: 100
  scoringAlgorithm: tfIdf

analyzer:
  strategy: default

  default:
    charFilters:
      - lowercase
      - punctuation
    tokenizer: whitespace
    tokenFilters:
      - stopwords

  fields:
    title:
      charFilters:
        - lowercase
        - punctuation
      tokenizer: whitespace
      tokenFilters:
        - stopwords

    body:
      charFilters:
        - lowercase
        - punctuation
      tokenizer: whitespace
      tokenFilters:
        - stopwords